import {faker} from '@faker-js/faker'

let user = '';
let password = '';
let port = '3001';
describe('new tags', () => {
    beforeEach(() => {
      
      cy.fixture('ghost.json').as('ghost')
      cy.fixture('ghost.json').then((data)  => {
          user = data.user
          password = data.password            
      })
      cy.visit(`http://localhost:${port}/ghost/`)
      cy.wait(2000)
               
      
    })
    it('Invite staff author with correct email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email())
            cy.get('#new-user-role').select('Author')
            cy.contains('Send invitation now').click()
            cy.wait(2000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff admin with correct email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email())
            cy.get('#new-user-role').select('Administrator')
            cy.contains('Send invitation now').click()
            cy.wait(2000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff contributor with correct email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email())
            cy.get('#new-user-role').select('Contributor')
            cy.contains('Send invitation now').click()
            cy.wait(2000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff editor with correct email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email())
            cy.get('#new-user-role').select('Editor')
            cy.contains('Send invitation now').click()
            cy.wait(2000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with incorrect email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email('Jeanne', 'Doe', '@gmail@gmail', { allowSpecialCharacters: true }))
            cy.get('#new-user-role').select('Author')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff admin with incorrect email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email('Jeanne', 'Doe', '@gmail@gmail', { allowSpecialCharacters: true }))
            cy.get('#new-user-role').select('Administrator')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff contributor with incorrect email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email('Jeanne', 'Doe', '@gmail@gmail', { allowSpecialCharacters: true }))
            cy.get('#new-user-role').select('Contributor')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff editor with incorrect email', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.internet.email('Jeanne', 'Doe', '@gmail@gmail', { allowSpecialCharacters: true }))
            cy.get('#new-user-role').select('Editor')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with incorrect email, no @', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.random.word()+'gmail.com')
            cy.get('#new-user-role').select('Author')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with incorrect email, no domain', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.random.word()+'@')
            cy.get('#new-user-role').select('Author')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with incorrect email, double @', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type(faker.random.word()+'@@gmail.com')
            cy.get('#new-user-role').select('Author')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with email length > 74', () => {       
            let emailTest= faker.lorem.slug(20)
           
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type( emailTest.substring(0,65) + "@gmail.com")
            cy.get('#new-user-role').select('Author')
            cy.get('fieldset > div > p').eq(0).contains('Invalid Email.')
            cy.wait(1000)
            cy.get('section > a > svg > path').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Invite staff author with email length = 74', () => {       
            let emailTest= faker.lorem.slug(20)
           
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/staff/"]').eq(0).click()
            cy.wait(100)
            cy.contains('Invite people').click()
            cy.get('#new-user-email').type( emailTest.substring(0,64) + "@gmail.com")
            cy.get('#new-user-role').select('Author')
            cy.wait(500)
            cy.contains('Send invitation now').click()
            cy.wait(1000)
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()

        })
        
    })

    
    