import {faker} from '@faker-js/faker'

let user = '';
let password = '';
let port = '3001';
let tagName = '';
describe('new tags', () => {
    beforeEach(() => {
      
      cy.fixture('ghost.json').as('ghost')
      cy.fixture('ghost.json').then((data)  => {
          user = data.user
          password = data.password            
      })
      cy.visit(`http://localhost:${port}/ghost/`)
      cy.wait(2000)
      tagName = faker.lorem.sentence(100)
          

    })
    it('Create a new tag with tag color 2 character', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(100)
            cy.contains('New tag').click()            
            cy.get('#tag-name').type(faker.datatype.string(10))
            cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
            cy.wait(100)
            cy.get('input[name="accent-color"]').type(faker.datatype.number({ max: 99 }))
            cy.wait(100)
            cy.get('#tag-slug').click()
            cy.wait(1000)
            cy.get('span > p:nth-child(2)').eq(0).contains('The color should be in valid hex format')
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Create a new tag with tag color 3 character', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(100)
            cy.contains('New tag').click()            
            cy.get('#tag-name').type(faker.datatype.string(10))
            cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
            cy.wait(100)
            cy.get('input[name="accent-color"]').type(faker.datatype.number({ max: 999 }))
            cy.wait(100)
            cy.get('#tag-slug').click()
            cy.wait(1000)
            cy.get('span > p:nth-child(2)').eq(0).contains('The color should be in valid hex format')
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Create a new tag with tag color 4 character', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(100)
            cy.contains('New tag').click()            
            cy.get('#tag-name').type(faker.datatype.string(10))
            cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
            cy.wait(100)
            cy.get('input[name="accent-color"]').type(faker.datatype.number({ max: 9999 }))
            cy.wait(100)
            cy.get('#tag-slug').click()
            cy.wait(1000)
            cy.get('span > p:nth-child(2)').eq(0).contains('The color should be in valid hex format')
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Create a new tag with tag color 5 character', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(100)
            cy.contains('New tag').click()            
            cy.get('#tag-name').type(faker.datatype.string(10))
            cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
            cy.wait(100)
            cy.get('input[name="accent-color"]').type(faker.datatype.number({ max: 99999 }))
            cy.wait(100)
            cy.get('#tag-slug').click()
            cy.wait(1000)
            cy.get('span > p:nth-child(2)').eq(0).contains('The color should be in valid hex format')
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Create a new tag with tag color 6 character', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(100)
            cy.contains('New tag').click()            
            cy.get('#tag-name').type(faker.datatype.string(10))
            cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
            cy.wait(100)
            cy.get('input[name="accent-color"]').type(faker.datatype.number({ max: 999999 }))
            cy.wait(100)
            cy.get('#tag-slug').click()
            cy.wait(1000)            
            cy.contains('Save').click()
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
        })

        it('Create a new tag with tag name > 191 characters', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(500)
            cy.contains('New tag').click()
            cy.wait(500)                      
            cy.get('#tag-name').type(tagName.substring(0,192))
            cy.wait(1000)            
            cy.contains('Save').click()
            cy.wait(100)                
            cy.get('span > p:nth-child(1)').eq(0).contains('Tag names cannot be longer than 191 characters. ')            
            cy.wait(100)            
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
            cy.wait(100)
            cy.contains('Leave').click()

        })
        it('Create a new tag with tag name = 191 characters', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(500)
            cy.contains('New tag').click()
            cy.wait(500)                      
            cy.get('#tag-name').type(tagName.substring(0,191))
            cy.wait(1000)            
            cy.contains('Save').click()
            cy.wait(100)                
            //cy.get('span > p:nth-child(1)').eq(0).contains('Tag names cannot be longer than 191 characters. ')            
            //cy.wait(100)            
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
            
        })

        it('Create a new tag with slug > 191 characters', () => {       
            cy.get('#ember8').type(user)
            cy.get('#ember10').type(password)
            cy.get('#ember12').click()        
            cy.url().should('eq', `http://localhost:${port}/ghost/#/site`)
            cy.get('a[href="#/tags/"]').eq(0).click()
            cy.wait(500)
            cy.contains('New tag').click()
            cy.wait(500)                      
            cy.get('#tag-name').type(tagName.substring(0,191))
            cy.wait(1000)
            cy.get('#tag-slug').type(tagName.substring(0,192))
            cy.contains('Save').click()
            cy.wait(100)
            cy.contains('Retry')      
            cy.get('div.gh-nav-bottom').click()
            cy.wait(100)
            cy.get('a[href="#/signout/"]').click()
            cy.wait(100)
            cy.contains('Leave').click()
            
        })
    })

    
    